-- DecideTab Fase 1 - Seed inicial
DROP TABLE IF EXISTS percentile_norms;
DROP TABLE IF EXISTS careers;
DROP TABLE IF EXISTS socioeconomic_questions;
DROP TABLE IF EXISTS hereford_items;

CREATE TABLE hereford_items (
  id SERIAL PRIMARY KEY,
  item_number INT NOT NULL UNIQUE,
  text TEXT NOT NULL,
  area CHAR(1) NOT NULL
);

CREATE TABLE socioeconomic_questions (
  id SERIAL PRIMARY KEY,
  section TEXT NOT NULL,
  question_number INT NOT NULL UNIQUE,
  question_text TEXT NOT NULL,
  options JSONB NOT NULL
);

CREATE TABLE careers (
  id SERIAL PRIMARY KEY,
  area_hereford CHAR(1) NOT NULL,
  career_name TEXT NOT NULL,
  university TEXT NOT NULL,
  monthly_cost_approx NUMERIC(10,2),
  modality TEXT NOT NULL,
  official_link TEXT,
  is_public BOOLEAN DEFAULT FALSE
);

CREATE TABLE percentile_norms (
  id SERIAL PRIMARY KEY,
  area CHAR(1) NOT NULL,
  sex CHAR(1) NOT NULL,
  percentile INT NOT NULL,
  raw_score INT NOT NULL
);

INSERT INTO hereford_items (item_number, text, area) VALUES
(1, 'Reparar una plancha', 'D'),
(2, 'Participar en discusiones en Consejo de curso', 'H'),
(3, 'Resolver rompecabezas numéricas', 'A'),
(4, 'Aprender a leer música', 'I'),
(5, 'Estudiar pequeños elementos con el microscopio', 'C'),
(6, 'Visitar enfermos', 'E'),
(7, 'Pintar países', 'H'),
(8, 'Observar los satélites y eclipses', 'B'),
(9, 'Escribir cuentos para una revista', 'F'),
(10, 'Recibir un juego de pintura como regalo', 'H'),
(11, 'Ejecutar operaciones aritméticas', 'A'),
(12, 'Leer novelas', 'F'),
(13, 'Participar en campañas contra la delincuencia juvenil', 'E'),
(14, 'Recibir un telescopio como regalo', 'B'),
(15, 'Saber distinguir y apreciar la buena música', 'I'),
(16, 'Manejar un torno o taladro eléctrico', 'D'),
(17, 'Discutir sobre políticas', 'G'),
(18, 'Coleccionar plantas', 'C'),
(19, 'Ayudar al prójimo', 'E'),
(20, 'Asistir a exposiciones de pintura', 'H'),
(21, 'Enseñar a los compañeros atrasados', 'E'),
(22, 'Medir ángulos de geometría', 'A'),
(23, 'Utilizar máquinas de cálculos', 'A'),
(24, 'Aprender primeros auxilios', 'E'),
(25, 'Leer novelas de escritores famosos', 'F'),
(26, 'Hacer diseños', 'H'),
(27, 'Hacer campañas estudiantiles', 'G'),
(28, 'Distinguir y apreciar la buena literatura', 'F'),
(29, 'Ayudar a buscar empleos a personas de escasos recursos', 'E'),
(30, 'Informarse sobre el uso de la energía atómica', 'B'),
(31, 'Leer libros sobre arte', 'H'),
(32, 'Realizar cálculos con distintas medidas', 'A'),
(33, 'Escuchar conciertos en las plazas públicas', 'I'),
(34, 'Hacer una instalación eléctrica', 'D'),
(35, 'Convencer a otros para que hagan lo que tú crees que es mejor', 'G'),
(36, 'Criar animales o aves', 'C'),
(37, 'Usar una calculadora', 'A'),
(38, 'Hacer propaganda a nuevos productos', 'G'),
(39, 'Coleccionar minerales', 'B'),
(40, 'Observar y estudiar la vida de las hormigas', 'C'),
(41, 'Obtener el autógrafo de un músico famoso', 'I'),
(42, 'Asistir a biblioteca en los momentos libres', 'F'),
(43, 'Observar a un técnico reparar televisión', 'D'),
(44, 'Decorar escenarios', 'H'),
(45, 'Observar y estudiar los astros y planetas', 'B'),
(46, 'Realizar trabajos de soldadura', 'D'),
(47, 'Defender las opiniones de otra persona', 'G'),
(48, 'Realizar cálculos de porcentajes', 'A'),
(49, 'Servir como consejero en clubes infantiles y juveniles', 'E'),
(50, 'Hacer mosaicos artísticos para decorar', 'H'),
(51, 'Asistir a una operación médica', 'C'),
(52, 'Participar en concursos literarios', 'F'),
(53, 'Estudiar el aspecto luminoso de la luz', 'B'),
(54, 'Asistir a conciertos', 'I'),
(55, 'Ser el líder del grupo', 'G'),
(56, 'Ayudar a los inválidos', 'E'),
(57, 'Visitar una exposición científica', 'B'),
(58, 'Diseñar trajes', 'H'),
(59, 'Consultar tablas de logaritmos y raíces', 'A'),
(60, 'Estudiar la música de diferentes países, como la India y Japón', 'I'),
(61, 'Informarte sobre el desarrollo de un ser vivo', 'C'),
(62, 'Corregir composiciones o artículos periodísticos', 'F'),
(63, 'Observar a los mecánicos cuando reparan un carro', 'D'),
(64, 'Ayudar a otras personas en problemas aritméticos', 'A'),
(65, 'Dibujar personas o cosas', 'H'),
(66, 'Desarmar y armar un reloj', 'D'),
(67, 'Leer libros y comentarios', 'F'),
(68, 'Estudiar los fenómenos atmosféricos y sus causas', 'B'),
(69, 'Coleccionar insectos', 'C'),
(70, 'Formar parte de un conjunto coral', 'I'),
(71, 'Conversar y escuchar a otros con paciencia', 'E'),
(72, 'Organizar y dirigir excursiones, festivales o campañas sociales', 'G'),
(73, 'Construir cuerpos geométricos con ayuda de escuadra y compás', 'A'),
(74, 'Tocar un instrumento musical', 'I'),
(75, 'Dirigir un grupo para ayudar a resolver problemas', 'G'),
(76, 'Cultivar plantas exóticas', 'C'),
(77, 'Visitar casas humildes para saber lo que necesitan', 'E'),
(78, 'Escribir un diario de vida', 'F'),
(79, 'Arreglar muebles', 'D'),
(80, 'Saber distinguir y apreciar las buenas pinturas', 'H'),
(81, 'Visitar un observatorio astronómico', 'B'),
(82, 'Observar cómo se arma una máquina', 'D'),
(83, 'Escribir editoriales o artículos periodísticos', 'F'),
(84, 'Realizar experimentos científicos', 'B'),
(85, 'Aportar con ideas para decorar una casa', 'H'),
(86, 'Cuidar de los hermanos menores', 'E'),
(87, 'Hacer propaganda de un nuevo producto', 'G'),
(88, 'Resolver problemas de matemáticas', 'A'),
(89, 'Ser compositor de música', 'I'),
(90, 'Observar la vida de algunos insectos', 'C');

INSERT INTO socioeconomic_questions (section, question_number, question_text, options) VALUES
('Situación Financiera', 1, '¿Quién financiará tus estudios?', '[{"value": "padre_madre", "label": "Padre/Madre"}, {"value": "tutor_familiares", "label": "Tutor/Otros familiares"}, {"value": "recursos_propios", "label": "Recursos propios"}, {"value": "beca_externa", "label": "Beca externa"}]'::jsonb),
('Situación Financiera', 2, 'Ingreso mensual total hogar', '[{"value": "lt_5000", "label": "Menos de $5,000"}, {"value": "5000_10000", "label": "$5,000–$10,000"}, {"value": "10001_20000", "label": "$10,001–$20,000"}, {"value": "gt_20000", "label": "Más de $20,000"}]'::jsonb),
('Situación Financiera', 3, 'Presupuesto máximo mensual colegiatura', '[{"value": "A", "label": "Rango A: Menos de $1,500"}, {"value": "B", "label": "Rango B: $1,500–$4,000"}, {"value": "C", "label": "Rango C: Más de $4,000"}]'::jsonb),
('Logística', 4, '¿Planeas trabajar?', '[{"value": "si_completo", "label": "Sí jornada completa"}, {"value": "si_medio", "label": "Sí medio tiempo"}, {"value": "no_solo_estudiar", "label": "No, solo estudiar"}]'::jsonb),
('Logística', 5, '¿Equipo de cómputo?', '[{"value": "si", "label": "Sí"}, {"value": "no", "label": "No"}, {"value": "solo_movil", "label": "Solo internet móvil"}]'::jsonb),
('Logística', 6, 'Disponibilidad traslado', '[{"value": "villahermosa", "label": "Puedo trasladarme a Villahermosa"}, {"value": "en_linea", "label": "Requiero en línea"}, {"value": "fines_semana", "label": "Solo fines de semana"}]'::jsonb),
('Apoyos', 7, '¿Beca Benito Juárez?', '[{"value": "si", "label": "Sí"}, {"value": "no", "label": "No"}]'::jsonb),
('Apoyos', 8, '¿Promedio > 8.5?', '[{"value": "si", "label": "Sí"}, {"value": "no", "label": "No"}]'::jsonb);

INSERT INTO percentile_norms (area, sex, percentile, raw_score) VALUES
('A', 'M', 99, 50),
('A', 'F', 99, 49),
('B', 'M', 99, 49),
('B', 'F', 99, 48),
('C', 'M', 99, 50),
('C', 'F', 99, 49),
('D', 'M', 99, 47),
('D', 'F', 99, 48),
('E', 'M', 99, 49),
('E', 'F', 99, 46),
('F', 'M', 99, 49),
('F', 'F', 99, 46),
('G', 'M', 99, 48),
('G', 'F', 99, 48),
('H', 'M', 99, 50),
('H', 'F', 99, 47),
('I', 'M', 99, 49),
('I', 'F', 99, 47),
('A', 'M', 95, 48),
('A', 'F', 95, 48),
('B', 'M', 95, 46),
('B', 'F', 95, 46),
('C', 'M', 95, 46),
('C', 'F', 95, 47),
('D', 'M', 95, 47),
('D', 'F', 95, 42),
('E', 'M', 95, 43),
('E', 'F', 95, 47),
('F', 'M', 95, 42),
('F', 'F', 95, 46),
('G', 'M', 95, 42),
('G', 'F', 95, 45),
('H', 'M', 95, 45),
('H', 'F', 95, 48),
('I', 'M', 95, 43),
('I', 'F', 95, 47),
('A', 'M', 90, 47),
('A', 'F', 90, 45),
('B', 'M', 90, 44),
('B', 'F', 90, 43),
('C', 'M', 90, 44),
('C', 'F', 90, 45),
('D', 'M', 90, 45),
('D', 'F', 90, 39),
('E', 'M', 90, 41),
('E', 'F', 90, 46),
('F', 'M', 90, 40),
('F', 'F', 90, 43),
('G', 'M', 90, 39),
('G', 'F', 90, 41),
('H', 'M', 90, 42),
('H', 'F', 90, 47),
('I', 'M', 90, 40),
('I', 'F', 90, 45),
('A', 'M', 80, 44),
('A', 'F', 80, 41),
('B', 'M', 80, 41),
('B', 'F', 80, 40),
('C', 'M', 80, 40),
('C', 'F', 80, 40),
('D', 'M', 80, 42),
('D', 'F', 80, 36),
('E', 'M', 80, 39),
('E', 'F', 80, 44),
('F', 'M', 80, 37),
('F', 'F', 80, 40),
('G', 'M', 80, 37),
('G', 'F', 80, 37),
('H', 'M', 80, 39),
('H', 'F', 80, 43),
('I', 'M', 80, 38),
('I', 'F', 80, 42),
('A', 'M', 70, 42),
('A', 'F', 70, 37),
('B', 'M', 70, 39),
('B', 'F', 70, 38),
('C', 'M', 70, 37),
('C', 'F', 70, 38),
('D', 'M', 70, 40),
('D', 'F', 70, 32),
('E', 'M', 70, 37),
('E', 'F', 70, 42),
('F', 'M', 70, 35),
('F', 'F', 70, 38),
('G', 'M', 70, 35),
('G', 'F', 70, 35),
('H', 'M', 70, 36),
('H', 'F', 70, 40),
('I', 'M', 70, 36),
('I', 'F', 70, 40),
('A', 'M', 60, 39),
('A', 'F', 60, 33),
('B', 'M', 60, 38),
('B', 'F', 60, 36),
('C', 'M', 60, 35),
('C', 'F', 60, 36),
('D', 'M', 60, 38),
('D', 'F', 60, 30),
('E', 'M', 60, 36),
('E', 'F', 60, 40),
('F', 'M', 60, 33),
('F', 'F', 60, 36),
('G', 'M', 60, 33),
('G', 'F', 60, 33),
('H', 'M', 60, 33),
('H', 'F', 60, 37),
('I', 'M', 60, 34),
('I', 'F', 60, 38),
('A', 'M', 50, 37),
('A', 'F', 50, 30),
('B', 'M', 50, 36),
('B', 'F', 50, 34),
('C', 'M', 50, 32),
('C', 'F', 50, 34),
('D', 'M', 50, 36),
('D', 'F', 50, 28),
('E', 'M', 50, 34),
('E', 'F', 50, 38),
('F', 'M', 50, 32),
('F', 'F', 50, 34),
('G', 'M', 50, 31),
('G', 'F', 50, 31),
('H', 'M', 50, 35),
('H', 'F', 50, 33),
('I', 'M', 50, 37),
('I', 'F', 50, 36),
('A', 'M', 40, 34),
('A', 'F', 40, 26),
('B', 'M', 40, 34),
('B', 'F', 40, 32),
('C', 'M', 40, 29),
('C', 'F', 40, 31),
('D', 'M', 40, 34),
('D', 'F', 40, 26),
('E', 'M', 40, 32),
('E', 'F', 40, 37),
('F', 'M', 40, 30),
('F', 'F', 40, 32),
('G', 'M', 40, 29),
('G', 'F', 40, 29),
('H', 'M', 40, 30),
('H', 'F', 40, 34),
('I', 'M', 40, 31),
('I', 'F', 40, 36),
('A', 'M', 30, 30),
('A', 'F', 30, 23),
('B', 'M', 30, 32),
('B', 'F', 30, 29),
('C', 'M', 30, 27),
('C', 'F', 30, 29),
('D', 'M', 30, 32),
('D', 'F', 30, 24),
('E', 'M', 30, 31),
('E', 'F', 30, 35),
('F', 'M', 30, 28),
('F', 'F', 30, 30),
('G', 'M', 30, 27),
('G', 'F', 30, 28),
('H', 'M', 30, 28),
('H', 'F', 30, 32),
('I', 'M', 30, 29),
('I', 'F', 30, 35),
('A', 'M', 20, 25),
('A', 'F', 20, 20),
('B', 'M', 20, 30),
('B', 'F', 20, 27),
('C', 'M', 20, 26),
('C', 'F', 20, 26),
('D', 'M', 20, 30),
('D', 'F', 20, 22),
('E', 'M', 20, 29),
('E', 'F', 20, 33),
('F', 'M', 20, 26),
('F', 'F', 20, 28),
('G', 'M', 20, 25),
('G', 'F', 20, 26),
('H', 'M', 20, 26),
('H', 'F', 20, 30),
('I', 'M', 20, 26),
('I', 'F', 20, 32),
('A', 'M', 10, 10),
('A', 'F', 10, 17),
('B', 'M', 10, 27),
('B', 'F', 10, 23),
('C', 'M', 10, 22),
('C', 'F', 10, 24),
('D', 'M', 10, 26),
('D', 'F', 10, 20),
('E', 'M', 10, 24),
('E', 'F', 10, 27),
('F', 'M', 10, 30),
('F', 'F', 10, 23),
('G', 'M', 10, 25),
('G', 'F', 10, 23),
('H', 'M', 10, 23),
('H', 'F', 10, 27),
('I', 'M', 10, 23),
('I', 'F', 10, 28),
('A', 'M', 5, 17),
('A', 'F', 5, 14),
('B', 'M', 5, 24),
('B', 'F', 5, 22),
('C', 'M', 5, 20),
('C', 'F', 5, 22),
('D', 'M', 5, 22),
('D', 'F', 5, 18),
('E', 'M', 5, 27),
('E', 'F', 5, 24),
('F', 'M', 5, 28),
('F', 'F', 5, 22),
('G', 'M', 5, 24),
('G', 'F', 5, 22),
('H', 'M', 5, 20),
('H', 'F', 5, 21),
('I', 'M', 5, 25),
('I', 'F', 5, 21),
('A', 'M', 1, 12),
('A', 'F', 1, 11),
('B', 'M', 1, 18),
('B', 'F', 1, 18),
('C', 'M', 1, 15),
('C', 'F', 1, 16),
('D', 'M', 1, 16),
('D', 'F', 1, 15),
('E', 'M', 1, 15),
('E', 'F', 1, 19),
('F', 'M', 1, 25),
('F', 'F', 1, 15),
('G', 'M', 1, 12),
('G', 'F', 1, 18),
('H', 'M', 1, 15),
('H', 'F', 1, 18),
('I', 'M', 1, 20),
('I', 'F', 1, 16);

INSERT INTO careers (area_hereford, career_name, university, monthly_cost_approx, modality, official_link, is_public) VALUES
('A', 'Matemáticas', 'UJAT', 200, 'Presencial', NULL, TRUE),
('A', 'Actuaría', 'UJAT', 200, 'Presencial', NULL, TRUE),
('A', 'Actuaría', 'UVM', 16000, 'Presencial', NULL, FALSE),
('A', 'Contador Público (Online)', 'UAG', 5906, 'En línea', NULL, FALSE),
('A', 'Contaduría Pública', 'Alfa y Omega', 800, 'Sabatino', NULL, FALSE),
('B', 'Física', 'UJAT', 200, 'Presencial', NULL, TRUE),
('B', 'Ing. Química', 'UJAT', 200, 'Presencial', NULL, TRUE),
('B', 'Ing. Química', 'ITVH', 200, 'Presencial', NULL, TRUE),
('B', 'Ing. en Geología', 'UPCH', 774, 'Presencial', NULL, TRUE),
('B', 'Ing. en Física (Online)', 'UVM', 16000, 'En línea', NULL, FALSE),
('C', 'Biología', 'UJAT', 200, 'Presencial', NULL, TRUE),
('C', 'Médico Cirujano', 'UJAT', 200, 'Presencial', NULL, TRUE),
('C', 'Medicina', 'UVM', 17100, 'Presencial', NULL, FALSE),
('C', 'Nutrición', 'UVM', 16000, 'Presencial', NULL, FALSE),
('C', 'Nutrición', 'Vizcaya', 2100, 'Presencial', NULL, FALSE),
('D', 'Ing. Civil', 'UJAT', 200, 'Presencial', NULL, TRUE),
('D', 'Arquitectura', 'UJAT', 200, 'Presencial', NULL, TRUE),
('D', 'Ing. Petrolera', 'ITVH', 200, 'Presencial', NULL, TRUE),
('D', 'Ing. Mecatrónica', 'UVM', 16000, 'Presencial', NULL, FALSE),
('D', 'Arquitectura', 'Vizcaya', 2100, 'Presencial', NULL, FALSE),
('E', 'Cs. de la Educación', 'UJAT', 200, 'Presencial', NULL, TRUE),
('E', 'Psicología', 'UVM', 16000, 'Presencial', NULL, FALSE),
('E', 'Psicología', 'Vizcaya', 2100, 'Presencial', NULL, FALSE),
('E', 'Trabajo Social', 'Alfa y Omega', 800, 'Sabatino', NULL, FALSE),
('F', 'Idiomas', 'UJAT', 200, 'Presencial', NULL, TRUE),
('F', 'Comunicación', 'UJAT', 200, 'Presencial', NULL, TRUE),
('F', 'Comunicación y Medios Digitales', 'UVM', 16000, 'Presencial', NULL, FALSE),
('F', 'Historia (Online)', 'IEU', 4000, 'En línea', NULL, FALSE),
('G', 'Derecho', 'UJAT', 200, 'Presencial', NULL, TRUE),
('G', 'Administración', 'UJAT', 200, 'Presencial', NULL, TRUE),
('G', 'Derecho', 'UVM', 16000, 'Presencial', NULL, FALSE),
('G', 'Derecho (Online)', 'UAG', 7875, 'En línea', NULL, FALSE),
('G', 'Mercadotecnia', 'Esparta', 1000, 'Sabatino', NULL, FALSE),
('H', 'Gastronomía', 'UTTAB', 3473, 'Presencial', NULL, TRUE),
('H', 'Gastronomía', 'UVM', 16000, 'Presencial', NULL, FALSE),
('H', 'Diseño Gráfico Digital', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('H', 'Diseño de Modas', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('I', 'TSU en Música', 'UJAT', 200, 'Presencial', NULL, TRUE),
('I', 'Comunicación y Medios Digitales', 'UVM', 16000, 'Presencial', NULL, FALSE),
('I', 'Comunicación', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('A', 'Economía', 'UJAT', 200, 'Presencial', NULL, TRUE),
('A', 'Ing. en Gestión Empresarial', 'ITVH', 200, 'Presencial', NULL, TRUE),
('A', 'Ing. en Ciencia de Datos', 'ITVH', 200, 'Presencial', NULL, TRUE),
('A', 'Contaduría Pública y Finanzas', 'UVM', 16000, 'Presencial', NULL, FALSE),
('A', 'Ing. en Ciencia de Datos', 'UVM', 16000, 'Presencial', NULL, FALSE),
('A', 'Lic. en Administración Financiera (Online)', 'UAG', 5906, 'En línea', NULL, FALSE),
('A', 'Lic. en Comercio y Finanzas Internacionales', 'UPCH', 774, 'Presencial', NULL, TRUE),
('A', 'Lic. en Contaduría', 'UTTAB', 3473, 'Presencial', NULL, TRUE),
('A', 'Contaduría Pública', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('A', 'Contaduría Pública', 'IEU', 4000, 'Presencial', NULL, FALSE),
('A', 'Contaduría', 'Esparta', 1000, 'Sabatino', NULL, FALSE),
('B', 'Ing. Geofísica', 'UJAT', 200, 'Presencial', NULL, TRUE),
('B', 'Ing. Química', 'UTTAB', 3473, 'Presencial', NULL, TRUE),
('B', 'Ing. Química Petrolera', 'UPCH', 774, 'Presencial', NULL, TRUE),
('C', 'Cirujano Dentista', 'UJAT', 200, 'Presencial', NULL, TRUE),
('C', 'QFB', 'UJAT', 200, 'Presencial', NULL, TRUE),
('C', 'Medicina Veterinaria y Zootecnia', 'UJAT', 200, 'Presencial', NULL, TRUE),
('C', 'Ing. Bioquímica', 'ITVH', 200, 'Presencial', NULL, TRUE),
('C', 'Fisioterapia', 'UVM', 16000, 'Presencial', NULL, FALSE),
('C', 'QFB', 'UVM', 16000, 'Presencial', NULL, FALSE),
('C', 'Biotecnología', 'UVM', 16000, 'Presencial', NULL, FALSE),
('C', 'Ing. Biomédica', 'UVM', 16000, 'Presencial', NULL, FALSE),
('C', 'Médico Cirujano', 'UAG', 16000, 'Presencial', NULL, FALSE),
('C', 'QFB', 'UAG', 16000, 'Presencial', NULL, FALSE),
('C', 'Médico Cirujano', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('C', 'Odontología', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('C', 'Enfermería', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('C', 'Fisioterapia', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('D', 'Ing. Eléctrica y Electrónica', 'UJAT', 200, 'Presencial', NULL, TRUE),
('D', 'Ing. Mecánica Eléctrica', 'UJAT', 200, 'Presencial', NULL, TRUE),
('D', 'Ing. Civil', 'ITVH', 200, 'Presencial', NULL, TRUE),
('D', 'Ing. Industrial', 'ITVH', 200, 'Presencial', NULL, TRUE),
('D', 'Ing. en Energías Renovables', 'UPCH', 774, 'Presencial', NULL, TRUE),
('D', 'Ing. Eléctrica y Mecánica', 'UPCH', 774, 'Presencial', NULL, TRUE),
('D', 'Ing. Civil', 'UPCH', 774, 'Presencial', NULL, TRUE),
('D', 'Ing. en Mantenimiento Industrial', 'UTTAB', 3473, 'Presencial', NULL, TRUE),
('D', 'Ing. en Energía y Desarrollo Sostenible', 'UTTAB', 3473, 'Presencial', NULL, TRUE),
('D', 'Ing. Petrolera', 'UTTAB', 3473, 'Presencial', NULL, TRUE),
('D', 'Ing. Civil', 'UVM', 16000, 'Presencial', NULL, FALSE),
('D', 'Ing. Industrial y de Sistemas', 'UVM', 16000, 'Presencial', NULL, FALSE),
('D', 'Ing. Mecatrónica', 'UAG', 5906, 'En línea', NULL, FALSE),
('D', 'Ing. Civil', 'UAG', 16000, 'Presencial', NULL, FALSE),
('D', 'Arquitectura', 'UAG', 16000, 'Presencial', NULL, FALSE),
('D', 'Ing. Petrolera', 'Alfa y Omega', 800, 'Sabatino', NULL, FALSE),
('D', 'Ing. Industrial', 'Alfa y Omega', 800, 'Sabatino', NULL, FALSE),
('D', 'Arquitectura', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('D', 'Ing. Civil', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('D', 'Arquitectura', 'IEU', 4000, 'Presencial', NULL, FALSE),
('E', 'Sociología', 'UJAT', 200, 'Presencial', NULL, TRUE),
('E', 'Rehabilitación Física', 'UJAT', 200, 'Presencial', NULL, TRUE),
('E', 'Psicología Educativa', 'Alfa y Omega', 800, 'Sabatino', NULL, FALSE),
('E', 'Psicología Organizacional', 'Alfa y Omega', 800, 'Sabatino', NULL, FALSE),
('E', 'Pedagogía', 'Alfa y Omega', 800, 'Sabatino', NULL, FALSE),
('E', 'Pedagogía', 'UVM', 16000, 'Presencial', NULL, FALSE),
('E', 'Educación', 'UVM', 16000, 'Presencial', NULL, FALSE),
('E', 'Lic. en Educación', 'Esparta', 1000, 'Sabatino', NULL, FALSE),
('E', 'Tecnología Educativa', 'Esparta', 1000, 'Sabatino', NULL, FALSE),
('E', 'Trabajo Social', 'Esparta', 1000, 'Sabatino', NULL, FALSE),
('E', 'Cs. de la Educación', 'Vizcaya', 2100, 'Presencial', NULL, FALSE),
('E', 'Fisioterapia', 'Vizcaya', 2100, 'Presencial', NULL, FALSE),
('E', 'Psicopedagogía', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('E', 'Psicología', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('F', 'Historia', 'UJAT', 200, 'Presencial', NULL, TRUE),
('F', 'Desarrollo Cultural', 'UJAT', 200, 'Abierto', NULL, TRUE),
('F', 'Lenguas Extranjeras', 'UVM', 16000, 'Presencial', NULL, FALSE),
('F', 'Relaciones Internacionales', 'UVM', 16000, 'Presencial', NULL, FALSE),
('F', 'Lic. en Idiomas', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('F', 'Lengua y Literatura (Online)', 'IEU', 4000, 'En línea', NULL, FALSE),
('F', 'Lic. en Turismo Sostenible', 'UPCH', 774, 'Presencial', NULL, TRUE),
('G', 'Mercadotecnia', 'UJAT', 200, 'Presencial', NULL, TRUE),
('G', 'Criminología', 'UVM', 16000, 'Presencial', NULL, FALSE),
('G', 'Administración de Negocios Internacionales', 'UVM', 16000, 'Presencial', NULL, FALSE),
('G', 'Mercadotecnia', 'UVM', 16000, 'Presencial', NULL, FALSE),
('G', 'Negocios y Transformación Digital (Online)', 'UAG', 5906, 'En línea', NULL, FALSE),
('G', 'Comercio Internacional (Online)', 'UAG', 5906, 'En línea', NULL, FALSE),
('G', 'Cs. Política y Administración Pública', 'UPCH', 774, 'Presencial', NULL, TRUE),
('G', 'Negocios y Mercados Internacionales', 'UPCH', 774, 'Presencial', NULL, TRUE),
('G', 'Mercadotecnia', 'UPCH', 774, 'Presencial', NULL, TRUE),
('G', 'Gestión y Desarrollo Turístico', 'UTTAB', 3473, 'Presencial', NULL, TRUE),
('G', 'Mercadotecnia', 'UTTAB', 3473, 'Presencial', NULL, TRUE),
('G', 'Mercadotecnia', 'Vizcaya', 2100, 'Presencial', NULL, FALSE),
('G', 'Criminología y Criminalística', 'Vizcaya', 2100, 'Presencial', NULL, FALSE),
('G', 'Mercadotecnia Digital', 'UMMA', 4740, 'Presencial', NULL, FALSE),
('G', 'Ventas y Comercialización (Online)', 'IEU', 4000, 'En línea', NULL, FALSE),
('G', 'Criminología y Criminalística (Online)', 'IEU', 4000, 'En línea', NULL, FALSE),
('G', 'Cs. Políticas', 'Alfa y Omega', 800, 'Sabatino', NULL, FALSE),
('H', 'Gastronomía', 'IEU', 4000, 'Presencial', NULL, FALSE),
('H', 'Diseño de Moda e Industria del Vestido', 'UVM', 16000, 'Presencial', NULL, FALSE),
('H', 'Diseño Multimedia', 'UVM', 16000, 'Presencial', NULL, FALSE),
('H', 'Diseño y Comunicación Gráfica', 'UVM', 16000, 'Presencial', NULL, FALSE),
('H', 'Arquitectura de Interiores', 'IEU', 4000, 'Presencial', NULL, FALSE),
('H', 'Diseño y Comunicación Gráfica', 'IEU', 4000, 'Presencial', NULL, FALSE),
('H', 'Ing. en Diseño de Comunicación Digital', 'UAG', 16000, 'Presencial', NULL, FALSE),
('H', 'Lic. en Estilismo y Belleza Profesional', 'Esparta', 1000, 'Sabatino', NULL, FALSE),
